name: Build CMake/Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: get-cmake
        uses: lukka/get-cmake@latest

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.1
        with:
          install_runtime: false
          cache: true      
          stripdown: true

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..

      - name: Build
        run: cmake --build build --parallel 8
